version: "3"

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    container_name: api
    volumes:
      - .:/rails_docker_app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: "admin"
      DB_HOST: db
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/rails_docker_app
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    command: ["server", "/data", "--console-address", ":9001"]
volumes:
  db_data:
    driver: local
  bundle:
    driver: local
